### ISSUE TITLE
No mining and error print out ""If you are running a solo-mi.."

### ISSUE THREAD

**Issue by martinkrung** [zack-bitcoin/amoveo-c-miner#11]
I changed it to my public key and uncomented the line for your mining pool (159.89.106.253:8085) in miner.erl. Then I run run.sh and start with miner:start(). I use ubuntu.

I only get this error keep printing out: "If you are running a solo-mining node, then this error may have happened because you need to turn on and sync your Amoveo node before you can mine. 
 If this error happens while connected to the public mining node, then it can probably be safely ignored."

I did run it succesfuly once, on the first mainnet day. I even got 0.7 coin. Whats wrong now?

**Comment by zack-bitcoin** [comment]
The mining pool was probably turned off when you tried mining.
it should be working now.
