### ISSUE TITLE
Fast hash code logic

### ISSUE THREAD

**Issue by damoCl** [zack-bitcoin/amoveo-c-miner#12]
You need to update a 64 byte chunk, then save the ctx state. You then update the 2 bytes in the second chunk, and reset the state back to the saved ctx state on each iteration.

**Comment by zack-bitcoin** [comment]
It is about 10% faster with the change.

The code I have now calculates an identical hash as before. So I don't think it is taking the hash of a bunch of extra zeros.

The Sha256.c file looks like it pads the block with 8 bytes of stuff. So I only have 56 bytes left in a 64 byte block.

**Comment by damoCl** [comment]
No It's not taking a hash of extra zeroes, my mistake. Only when you call
sha256_final does  zeroes and get added, and the final hash get executed.
But your call to update with 56 bytes, doesn't do any work. update will
only do a cycle of sha256 once it has been has received 64 bytes.

So, it better give update 64 bytes if you have it.

You should be updating 64 bytes, then iterating in your while loop over the
last two bytes. Once you exit the loop, you can set the other bytes in you
nonce, and repeat.

**Comment by damoCl** [comment]
better no to use a while loop, change it to a for. You iterate over the
last one byte if you wanted to.

**Comment by zack-bitcoin** [comment]
Then why is this code 10% faster?
I think that SHA256 already has 8 bytes before I have added anything. So when I give it 56, that puts it over the 64 byte limit, and it computes the first block of the hash function.

**Comment by damoCl** [comment]
Check out my branch. Im in the process of testing it.

**Comment by zack-bitcoin** [comment]
I wrote a test. you are right. it is 2x faster the way you described.

**Comment by damoCl** [comment]
I'm still tearing my hair out. Stuck with test errors. I'll look at your
code tomorrow morning.

**Comment by damoCl** [comment]
Hi Zack,

I branched your amoveo- miner code to
https://github.com/damoCl/amoveo-c-miner.

I modified my sha256.c and sha256.h to open up a few functions for further
optimization. It's as fast as I can make it.

I may of accidentally requested a change to your branch, when I was just
trying to commit my own changes. I'm still new to github, so hopefully,
I'll get it soon.

Do you think the code can be used to optimise the GPU miner.  I would be
interested looking at the optimised GPU miner code you have.

Cheers
Damian.
