### ISSUE TITLE
The veo i minering is missing

### ISSUE THREAD

**Issue by sunbeyond40** [zack-bitcoin/amoveo-c-miner#14]
It is strange , I get  5.2 veo using c-miner,  I used to check it in http://amoveopool.com/.     but now i can't check it anymore , it seems that they are missing,   Why??

**Comment by zack-bitcoin** [comment]
I do not run that website.
They switched to a new location: http://amoveopool2.com/transaction

**Comment by sunbeyond40** [comment]
Ok , but i checking in http://amoveopool2.com/Wallet,    Find the "Veo Balance" still  show new , it seem all veo is missing.

**Comment by zack-bitcoin** [comment]
I do not run that website.
This is the wrong place to make this complaint.
