### ISSUE TITLE
Exception error on C miner

### ISSUE THREAD

**Issue by nextquick** [zack-bitcoin/amoveo-c-miner#2]
Hi Zack, for your information:

While I was:
- On computer A, windows 7:
   - mining from JS wallet to pubkey 1
- On computer B, ubuntu:
   - mining from c-miner to pubkey 1, connected to your 146.185.142.103 pool
   - running full node with pubkey 2, not minning

I got this on c-miner:
```
did not find a block in that period
did not find a block in that period
Found a block. 1

You need to turn on and sync your Amoveo node before you can mine. You can get it here: https://github.com/zack-bitcoin/amoveo
** exception error: no match of right hand side value 2
     in function  miner:talk_helper/3 (miner.erl, line 76)
     in call from miner:start_c_miners/1 (miner.erl, line 52)
2> miner:start().
Started mining.
did not find a block in that period
did not find a block in that period
Found a block. 1
Found a block. 2
did not find a block in that period
```

Quite strange since I suppose that the full node is not needed to run the c-miner, isn't it?

I restarted the c-miner and still working ok. Also tried to stop the node and still minning, as is supposed to be?

Let me know if you need any logfile.

Thanks

PS: is it possible to "autosync" the full node? Any command for this?

**Comment by zack-bitcoin** [comment]
Thank you for sharing this detailed report.

This happened because I forgot to turn on the mining pool on the server.
Or it crashed.

I will check it out.

**Comment by zack-bitcoin** [comment]
it looks like the mining pool is running as it should be.

I think this happened when I updated the code earlier today. For about 20 seconds I turned the node and mining pool off, and then restarted them with the new version of the software.
If you were mining during those 20 seconds, it could have disconnected your miners.

There are a couple ways we could fix this:
1) update the miner so that if the pool disappears, the miner waits for it to come back.
2) update the mining pool so that if we turn the off the amoveo full node, the mining pool waits for it to come back.

I think we should do both of these things. It will make the mining more resilient.

**Comment by zack-bitcoin** [comment]
I verified that mining is working from the browser. Which makes me more confident in my analysis of the situation.

**Comment by nextquick** [comment]
That sounds very feasible. It was a very short interruption indeed, I restarted the miner after about 2 minutes and it ran smooth again.
Thank you.

**Comment by nextquick** [comment]
This happened a while ago:


```
did not find a block in that period
Found a block. 1
Found a block. 2
did not find a block in that period
Found a block. 1

You need to turn on and sync your Amoveo node before you can mine. You can get it here: https://github.com/zack-bitcoin/amoveo
** exception error: no match of right hand side value 2
     in function  miner:talk_helper/3 (miner.erl, line 76)
     in call from miner:start_c_miners/1 (miner.erl, line 52)
3> did not find a block in that period
3> Found a block. 1
* 1: syntax error before: 'not'
3> 1
3>
3> You need to turn on and sync your Amoveo node before you can mine. You can get it here: https://github.com/zack-bitcoin/amoveo
* 3: syntax error before: You
3> You can get it here: https://github.com/zack-bitcoin/amoveo
3> ** exception error: no match of right hand side value 2
3>      in function  miner:talk_helper/3 (miner.erl, line 76)
3>      in call from miner:start_c_miners/1 (miner.erl, line 52)
3> 2> miner:start().
* 1: syntax error before: can
3> Started mining.
* 1: syntax error before: mining
3> did not find a block in that period
3> did not find a block in that period
3> Found a block. 1
* 1: syntax error before: 'not'
3> 1
3> Found a block. 2
* 2: syntax error before: Found
3> 2
3> did not find a block in that period
3>
```

**Comment by zack-bitcoin** [comment]
The internet is not perfect. Occasionally you are unable to connect to the server for no reason at all. And the mining software critically fails in this situation.

Thank you for sharing this report, this is an important error you uncovered.

I still think that the fix I suggested before will fix this.

**Comment by zack-bitcoin** [comment]
It is so weird how your computer is saying `syntax error before Found`.
The word `Found` is coming from a print statement.
It is like your computer is trying to run the print statement as a command or something.

Anyways, this commit https://github.com/zack-bitcoin/amoveo-c-miner/commit/239bb78ca1c59f949edcf6e29d08c26964d7285e
fixes the problem explained in this issue. So I will close this issue now.

**Comment by nextquick** [comment]
It seems to me that I copy&pasted part of the log over the erlang promt, sorry.

Maybe you'll have to output different messages depending on the target:
- "can't reach the pool, connection error"
- "can't reach the node, turn it on and sync before..."

**Comment by zack-bitcoin** [comment]
yeah, that might be a better way to do it.
Instead of commenting/uncommenting to switch who you connect to, there should be a config file where you can choose between 3 modes.
And the error message should also change depending on the mode.
